version: '2'
services:
  nodered:
    depends_on:
        - grafana
    image: nodered/node-red:latest
    environment:
        - TZ=Europe/Paris
    ports:
        - "1880:1880"
    volumes:
        - nodered-storage:/data
    restart: always  
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    restart: always 
  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - ./chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    restart: always 
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    user: "grafana"
    volumes:
      - grafana-storage:/var/lib/grafana
      - grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    restart: always
  hivemq:
    image: hivemq/hivemq4
    ports:
      - '1883:1883'
      - '8883:8883'
      - '8000:8000'
    restart: always
volumes:
  grafana-storage:
  grafana-provisioning:
  nodered-storage:

