
apiVersion: 1
datasources:
- orgId: 1
  version: 2
  name: InfluxDB
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  basicAuth: true
  isDefault: true
  jsonData:
    defaultBucket: pdr
    httpMode: POST
    organization: nb_iot
    version: Flux
  secureJsonData:
    token: 






