apiVersion: 1

datasources:
   - name: InfluxDB_v2_Flux
     type: influxdb
     access: proxy
     url: http://influxdb:8086
     jsonData:
        version: Flux
        organization: organization
        defaultBucket: bucket
        tlsSkipVerify: true
     secureJsonData:
         token: 'Qhf9U0X6wt6m9zYvhhFwldHO9Ne8RZ7GECAHTM-QDABMFq-qjJtacqy6zneVxVZ0uqUTAzXArk9-YEyiyvy7ig=='








