
version: "3"
services: 
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "mosquitto-data:/mosquitto"
  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - "node-red-data:/data"
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"        
    volumes:
      - "influxdb-data:/var/lib/influxdb"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=nb_iot
      - DOCKER_INFLUXDB_INIT_BUCKET=measures
  grafana:
    image: benayyad12/grafana-nb-iot:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "grafana-data:/var/lib/grafana"
volumes:
  influxdb-data:
  grafana-data:        
  node-red-data:
  mosquitto-data:
