
version: "3"
services: 
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "mosquitto-data:/mosquitto"
  node-red:
    image: node-red-custom:latest
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - "node-red-data:/data"
  influxdb:
    image: influxdb-custom
    container_name: influxdb
    ports:
      - "8086:8086"        
    volumes:
      - "influxdb-data:/var/lib/influxdb"
  grafana:
    image: benayyad12/grafana-nb-iot
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "grafana-data:/var/lib/grafana"
volumes:
  influxdb-data:
  grafana-data:        
  node-red-data:
  mosquitto-data:
