
version: "3"
services: 
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "mosquitto-data:/mosquitto"
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf" 
  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
      - "1880:1880"
    devices:
      - /dev/tty.usbmodem14101:/dev/tty.usbmodem14101
    user: "root"
    volumes:
      - "node-red-data:/data"
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"        
    env_file:
      - 'influxdb.env'
    volumes:
      - "influxdb-data:/var/lib/influxdb"
  grafana:
    image: benayyad12/grafana-nb-iot:latest 
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'grafana.env'
    user: "0"
    volumes:
      - "grafana-data:/var/lib/grafana"
volumes:
  influxdb-data:
  grafana-data:        
  node-red-data:
  mosquitto-data:
